### ISSUE TITLE
Import Failed,Is there a solution to this?

### ISSUE THREAD

**Issue by BoosterCore** [flowtyone/ComfyUI-Flowty-TripoSR#16]
`K:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --listen --output-directory "J:\ComfyUI_Output"
** ComfyUI startup time: 2024-03-06 21:34:45.850873
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: K:\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: K:\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.1 seconds: K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 130262 MB
xformers version: 0.0.24
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16`

`Traceback (most recent call last):
  File "K:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR\__init__.py", line 6, in <module>
    from tsr.system import TSR
  File "K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR\tsr\system.py", line 16, in <module>
    from .models.isosurface import MarchingCubeHelper
  File "K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR\tsr\models\isosurface.py", line 6, in <module>
    from torchmcubes import marching_cubes
ModuleNotFoundError: No module named 'torchmcubes'`

**Comment by BoosterCore** [comment]
The problem has been solved
