### ISSUE TITLE
导入你的LayerDIffusion + TripoSR【Zho】.json 工作流黑屏，无法解决，layer_diffusion正常，triposr正常

### ISSUE THREAD

**Issue by kungful** [flowtyone/ComfyUI-Flowty-TripoSR#23]
![微信图片_20240307184639](https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/assets/84950880/05fe310a-5a90-4dec-87e2-bc09ba0ce637)

**Comment by kungful** [comment]
D:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI startup time: 2024-03-07 18:51:43.648799
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: D:\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: D:\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.1 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 22528 MB, total RAM 32718 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools\__init__.py", line 10, in <module>
    from .core import version, logger
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools\core\__init__.py", line 5, in <module>
    from .common import *
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools\core\common.py", line 4, in <module>
    from deepdiff import DeepDiff
ModuleNotFoundError: No module named 'deepdiff'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools module for custom nodes: No module named 'deepdiff'
D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Diffusers-X-Adapter-main\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Diffusers-X-Adapter-main\nodes.py", line 11, in <module>
    from .xadapter.model.unet_adapter import UNet2DConditionModel as UNet2DConditionModel_v2
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Diffusers-X-Adapter-main\xadapter\model\unet_adapter.py", line 39, in <module>
    from diffusers.models.unets.unet_2d_blocks import get_down_block, get_up_block, UNetMidBlock2DCrossAttn, UNetMidBlock2DSimpleCrossAttn
ModuleNotFoundError: No module named 'diffusers.models.unets'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Diffusers-X-Adapter-main module for custom nodes: No module named 'diffusers.models.unets'
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR-ZHO\__init__.py", line 7, in <module>
    from tsr.utils import remove_background, resize_foreground
ImportError: cannot import name 'remove_background' from 'tsr.utils' (D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR\tsr\utils.py)

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR-ZHO module for custom nodes: cannot import name 'remove_background' from 'tsr.utils' (D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR\tsr\utils.py)
### Loading: ComfyUI-Impact-Pack (V4.83.1)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Manager (V2.9)
### ComfyUI Revision: 2052 [55f37baa] | Released on '2024-03-07'
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr-main\__init__.py", line 2, in <module>
    from .vae import VAEDecodeBatched, VAEEncodeBatched
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr-main\vae.py", line 5, in <module>
    from .model.iter import try_get_iter
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr-main\model\iter.py", line 4, in <module>
    from comfy.sd import ModelPatcher, CLIP, VAE
ImportError: cannot import name 'ModelPatcher' from 'comfy.sd' (D:\ComfyUI_windows_portable\ComfyUI\comfy\sd.py)

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr-main module for custom nodes: cannot import name 'ModelPatcher' from 'comfy.sd' (D:\ComfyUI_windows_portable\ComfyUI\comfy\sd.py)
### Loading: Workspace Manager (V1.0.0)
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_roop\__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_roop\nodes.py", line 3, in <module>
    from scripts.faceswap import FaceSwapScript, get_models
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_roop\scripts\faceswap.py", line 16, in <module>
    from scripts.swapper import UpscaleOptions, swap_face, ImageResult
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_roop\scripts\swapper.py", line 12, in <module>
    import insightface
ModuleNotFoundError: No module named 'insightface'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_roop module for custom nodes: No module named 'insightface'
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Total VRAM 22528 MB, total RAM 32718 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
VAE dtype: torch.float32
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf\__init__.py", line 8, in <module>
    from custom_nodes.facerestore_cf.facelib.utils.face_restoration_helper import FaceRestoreHelper
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf\__init__.py", line 14, in <module>
    from custom_nodes.facerestore_cf.basicsr.utils.registry import ARCH_REGISTRY
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf\basicsr\__init__.py", line 5, in <module>
    from .losses import *
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf\basicsr\losses\__init__.py", line 5, in <module>
    from .losses import (CharbonnierLoss, GANLoss, L1Loss, MSELoss, PerceptualLoss, WeightedTVLoss, g_path_regularize,
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf\basicsr\losses\losses.py", line 2, in <module>
    import lpips
ModuleNotFoundError: No module named 'lpips'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf module for custom nodes: No module named 'lpips'

[rgthree] Loaded 34 extraordinary nodes.
[rgthree] Will use rgthree's optimized recursive execution.


Import times for custom nodes:
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_utility.py
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR-ZHO
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-tooling-nodes-main
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\wlsh_nodes
   0.0 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr-main
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-layerdiffusion
   0.0 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Studio-main
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\images-grid-comfy-plugin
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale-6ea48202a76ccf5904ddfa85f826efa80dd50520
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-workspace-manager
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_roop
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.1 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf
   0.1 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.2 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Diffusers-X-Adapter-main
   0.2 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ComfyWorkflows
   0.4 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-browser
   0.4 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.5 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.6 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR
   0.7 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
FETCH DATA from: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

**Comment by kungful** [comment]
> Please re-open this issue in the correct repository: https://github.com/ZHO-ZHO-ZHO/ComfyUI-Flowty-TripoSR-ZHO

Thanks for reminding
